apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:7.2.0
        ports:
        - containerPort: 8080
        env:
        - name: XPACK_MONITORING_ENABLED
          value: "true"
        - name: XPACK_MONITORING_ELASTICSEARCH_URL
          value: "http://nodea-service.default.svc.cluster.local:9200"
        - name: XPACK_MONITORING_ELASTICSEARCH_USERNAME
          value: "elastic"  
        - name: XPACK_MONITORING_ELASTICSEARCH_PASSWORD
          value: "changeme"