apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-stateful
spec:
  #clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  type: LoadBalancer