apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: http-db
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer